### ISSUE TITLE
QR Code Not Loading 

### ISSUE THREAD

**Issue by neanhunt** [backdrop-contrib/tfa_basic#10]
When attempting to setup TFA application on security/tfa/app-setup, the QR code image is not loading.  GoogleAuthenticator.php is referencing **chart.googleapis.com** to pull the image.  From reading on internet, it seems Google has decommissioned this.  As a test, we edited GoogleAuthenticator.php and replaced chart.googleapis.com with quickchart.io and image block would load again.  Don't know if this or other URL would be used as a fix for this.  We found this URL while reading of chart.googleapis.com being taken down.

![image](https://github.com/backdrop-contrib/tfa_basic/assets/152751192/f7846061-1810-4dd9-86d9-91537ec5b471)

**Comment by herbdool** [comment]
This is related to https://github.com/backdrop-contrib/tfa_basic/issues/3

The included `PHPGangsta_GoogleAuthenticator` PHP library has an update that uses a different API for generating the QRCode, but I think it's better to just bundle the qrcodejs. It's a bit dated but looks like folks are still using it plus this is only generating QR Codes for logged in users.
