### ISSUE TITLE
Provide email plugin so validation codes can be emailed

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/tfa_basic#4]
Based on discussion: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Two.20Factor.20Authentication

From Nate:

> SMS is fraught with problems from interception, device availability, SIM copying, and bad user training. Plus it means manually typing from one device to another (if it's not on the phone). Email has become a common option that's used by Steam, Slack, and Discord. It's funny that it's such a rudimentary option and yet seems to be the "newest" form of 2FA.
>
> Since you already need email working for password reset, supporting email as its own 2FA seems like a better idea than extending Twilio.

**Comment by neanhunt** [comment]
Dowloaded ZIP file with updates for issue #4 and added to module on server .  I am seeing the email option on the config screen and tried changing the default validation plugin to Email and have TOP as a fallback but I am not seeing an email option when I attempt to setup a test account with TFA.  I did run DB update and it showed an update was made for TFA plugin.
![image](https://github.com/backdrop-contrib/tfa_basic/assets/152751192/7f664c68-af17-4edf-97e5-1321aeef15c6)
![image](https://github.com/backdrop-contrib/tfa_basic/assets/152751192/8d6a8053-4a7c-4d80-b6fb-824a47e59a0a)

This is my first time testing so maybe I am doing something wrong?

**Comment by herbdool** [comment]
Thanks @neanhunt. After adding the code, running the database update, changing the configuration to have email enabled. Then you create a user. You'll then need to log in as that new user and the user needs to go to the Security tab and set up TFA. Only then will TFA be enabled for that user for the next time they log in.

Do you want to try testing that again?

**Comment by neanhunt** [comment]
I was using a test account but to re-test I was clearing the entries for the UID in all the TFA DB tables...thinking this would reset the account to re-test.  Also, where is the configuration to have email enabled...and by that, is this email configuration to allow the site to send email (which it is) or configuring email for the TFA module?
I had tried clearing the DB for a test user but when entering the username & password, it stays on the login screen.  Looking to see if a rule is interfering with this now.

**Comment by herbdool** [comment]
If you log into a test account, before that user sets up TFA they would see something like:

![2024-04-09 12 42 14 bd3 lndo site 884eb25191a9](https://github.com/backdrop-contrib/tfa_basic/assets/1071483/c5b49333-ca16-4744-8198-1362cb23a20f)

This workflow is the same for all the TFA plugins. If you're unfamiliar using TFA in general I suggest first testing it without this PR. Try using "Recovery Code" as your primary to easily try it out.

You can temporarily disable TFA (at admin/config/people/tfa) and then log in with the test account too. Then enable after logged in (stay logged in as admin in one browser and test in another, or in a private window).

**Comment by neanhunt** [comment]
We had setup doing TFA with a site we are working on this way:
1. Created a placeholder role to assign the user to to allow them to login.
2. Created a rule to route a logged in user with this placeholder role to /user/[user id)/security/tfa to prompt them to setup TFA
3. Created a rule to check if user logged in had this placeholder role and had TFA enabled, if so it removed the placeholder role and assigned a new role that required TFA

Our thinking was that creating a new account with an assigned role that required TFA would prevent them from logging in initially so we would give them a temporary role and route them to the TFA setup then have them login again and the rules we setup would update their role automatically to a role that requires TFA to get logged in.  Is this overdoing it?

**Comment by neanhunt** [comment]
To add to the previous comment, we did the steps above because what we have been seeing is if we try to login to an account with a role that is required to have TFA that is was immediately asking for the authentication token and did not allow us to setup TFA.  This is why we came up with using a temp role that would allow the user to setup TFA then had rules in place to update the role assigned to the account.

**Comment by herbdool** [comment]
@neanhunt sounds like you're describing something that could be a new issue. You've got a workaround but sound like it could be a new improvement. Please describe it in a new issue by going to https://github.com/backdrop-contrib/tfa/issues/new/choose and filling it out.

I'll keep this issue focused on adding the new email plugin.

**Comment by herbdool** [comment]
@neanhunt I'm not really sure where this left off. Did you manage to test it? I recommend testing it on a site that's not live. Then you can toggle different settings.

After applying the patch and running db update. Create a test user. You'll then need to log in as that new user and the user needs to go to the Security tab and set up TFA. Only then will TFA be enabled for that user for the next time they log in.

If the test user is being blocked because their role requires TFA, either remove that role temporarily, or disable TFA temporarily (main TFA settings page). Then have the test user log in and re-enable the TFA / add back the role. Then the test user can go to the Security tab.

I usually do this testing by opening a private window so I can have two sessions at the same time.

**Comment by neanhunt** [comment]
Sorry @herbdool, I haven't been looking at this...both my parents (elderly) have been ill so I have been focused on that and haven't been working on any web projects/issues.  I am hoping to get back at it soon but wanted to give you an update (and didn't want you to think I had disappeared...which I guess I did).
